version: "3"

services:

  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - "./dist:/webui"
      - "./conf.d:/etc/nginx/conf.d"
