/*
  This file is generated by Emacs.
*/
import "../css/index.css";
import Vue from "vue";

import BootstrapeVue from 'bootstrap-vue';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
import axios from 'axios';
import VueRouter from 'vue-router';
import VueAxios from 'vue-axios';
import Cookies from 'js-cookie';
import LoginView from "../view/LoginView.vue";
import RegisterView from "../view/RegisterView.vue";
import ChatView from "../view/ChatView.vue";

Vue.use(BootstrapeVue);
Vue.use(VueRouter);
Vue.use(VueAxios, axios);

let server = '/api',
    wsserver = `ws://${document.location.host}/chatsocket`;

const routes = [
    { name: 'login', path: '/login',
      component: LoginView, props: { server } },
    { name: 'register', path: '/register',
      component: RegisterView, props: { server }},
    { name: 'chat', path: '/chat',
      component: ChatView, props: { server:  wsserver }}
];

const router = new VueRouter({
    routes
});

new Vue({
    el: "#app",
    template: `
            <transition>
                <router-view></router-view>
            </transition>
`,
    mounted: function() {
        this.axios.defaults.withCredentials = true;
        if (!Cookies.get('_xsrf')) {
            this.axios.get(`${server}/fetch`);
        } else {
            this.axios.defaults.headers.common['X-Xsrftoken'] = Cookies.get('_xsrf');
        }
        if (Cookies.get('uid')) {
            this.$router.push({name: 'chat'});
        } else {
            this.$router.push({name: 'login'});
        }
    },
    router
});
