/*
  This file is generated by Emacs.
*/
import "../css/index.css";
import Vue from "vue";

import BootstrapeVue from 'bootstrap-vue';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
import axios from 'axios';
import VueRouter from 'vue-router';
import VueAxios from 'vue-axios';
import Cookies from 'js-cookie';
import LoginView from "../view/LoginView.vue";
import RegisterView from "../view/RegisterView.vue";
import ChatView from "../view/ChatView.vue";

Vue.use(BootstrapeVue);
Vue.use(VueRouter);
Vue.use(VueAxios, axios);

const routes = [

    { name: 'login', path: '/login', component: LoginView },
    { name: 'register', path: '/register', component: RegisterView },
    { name: 'chat', path: '/chat', component: ChatView }
];

const router = new VueRouter({
    routes
});

new Vue({
    el: "#app",
    template: `
            <transition>
                <router-view></router-view>
            </transition>
`,
    mounted: function() {
        if (Cookies.get('uid')) {
            this.$router.push({name: 'chat'});
        } else {
            this.$router.push({name: 'login'});
        }
    },
    router
});
